error: this task is defined multiple times
  --> $DIR/task-exception.rs:10:8
   |
10 |     fn foo(_: foo::Context) {}
   |        ^^^

error: aborting due to previous error

